package com.blackjack;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class Deck {

    public String[] Deck(){
        Cards cards = new Cards();
        String[] color = cards.Colors();
        String[] suit = cards.Suits();
        String[] value = cards.Value();
        String[][][] allcards = cards.cards(color,suit,value);
        String[] fulldeck = filldeck(allcards);
        String[] shuffleddeck = Shuffle(fulldeck);
        return shuffleddeck;

    }

public String[] filldeck(String[][][] cards){
    String[] Deck = new String[96];

    int counter = 0;
    int temp = 0;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][0][temp];
    counter++;
    temp=0;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][0][temp];
    counter++;
    temp=0;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][1][temp];
    counter++;
    temp=0;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][1][temp];
    counter++;
    temp=0;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][2][temp];
    counter++;
    temp=0;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][2][temp];
    counter++;
    temp=0;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[0][3][temp];
    counter++;
    temp=0;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];
    counter++;
    temp++;
    Deck[counter] = cards[1][3][temp];

    counter = 0;
    for(int i=0; i>13; i++) {
        Deck[temp] = cards[1][0][counter];
        counter++;
        temp++;
    }
    counter = 0;
    for(int i=0; i>13; i++) {
        Deck[temp] = cards[0][1][counter];
        counter++;
        temp++;
    }

    return Deck;
}

// make shuffle function work
    public String[] Shuffle(String[] Deck){
        List<String> List = Arrays.asList(Deck);

        Collections.shuffle(List);

        List.toArray(Deck);

        return Deck;

    }


}
